services:
  - type: web
    name: phishing-sim
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 2 --preload
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: BREVO_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
